version: "3.9"

services:
  postgres:
    image: postgres:latest

    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - ".env"
    ports:
      - "5432:5432"
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: "make run"
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=postgres
    ports:
      - "8000:8000"
    


volumes:
  redis:
  redis-config:
  postgres-data:
