version: "3.9"

services:
  postgres:
    image: postgres:latest

    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - ".env"
    ports:
      - "5432:5432"


volumes:
  redis:
  redis-config:
  postgres-data:
