"""Algorithm_uuid

Revision ID: 002
Revises: 001
Create Date: 2023-12-06 01:25:14.936257

"""
from typing import Optional, Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "002"
down_revision: Optional[str] = "001"
branch_labels: Optional[Sequence[str]] = None
depends_on: Optional[Sequence[str]] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("algorithms", sa.Column("uuid", sa.UUID(), nullable=False))
    op.create_index(op.f("ix_algorithms_uuid"), "algorithms", ["uuid"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_algorithms_uuid"), table_name="algorithms")
    op.drop_column("algorithms", "uuid")
    # ### end Alembic commands ###
