"""version_uuid

Revision ID: 004
Revises: 003
Create Date: 2023-12-08 17:39:25.618491

"""
from typing import Optional, Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "004"
down_revision: Optional[str] = "003"
branch_labels: Optional[Sequence[str]] = None
depends_on: Optional[Sequence[str]] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("algorithm_versions", sa.Column("uuid", sa.UUID(), nullable=False))
    op.create_index(
        op.f("ix_algorithm_versions_uuid"), "algorithm_versions", ["uuid"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_algorithm_versions_uuid"), table_name="algorithm_versions")
    op.drop_column("algorithm_versions", "uuid")
    # ### end Alembic commands ###
