"""added_model_type

Revision ID: 005
Revises: 004
Create Date: 2023-12-09 10:02:38.552172

"""
from typing import Optional, Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "005"
down_revision: Optional[str] = "004"
branch_labels: Optional[Sequence[str]] = None
depends_on: Optional[Sequence[str]] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("algorithms", sa.Column("algo_type", sa.String(length=4), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("algorithms", "algo_type")
    # ### end Alembic commands ###
